ci: Add scheduled pipeline that disabled fail-fast strategy and always runs tests

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -5,12 +5,20 @@ on:
     branches: [ main ]
   pull_request:
     branches: [ main ]
+  schedule:
+    - cron: '0 20 * * 2'
+      timezone: Europe/Zurich
   workflow_dispatch:
     inputs:
       force-tests:
         description: 'Force build/test even if version is already published'
         required: false
-        default: 'false'
+        default: false
+        type: boolean
+      strategy-fail-fast:
+        description: 'Keep matrix fail-fast enabled (set false to continue running remaining matrix jobs after a failure)'
+        required: false
+        default: true
         type: boolean
 
 env:
@@ -21,6 +29,10 @@ jobs:
   # Build Job
   build:
     strategy:
+      # we want to fail-fast unless:
+      # - workflow inputs specifies not to fail-fast
+      # - scheduled build
+      fail-fast: ${{ github.event_name != 'schedule' && (github.event_name != 'workflow_dispatch' || inputs.strategy-fail-fast) }}
       matrix:
         feature: [
           "browsers",
@@ -76,36 +88,36 @@ jobs:
       - name: Check if version already published
         id: check-version
         run: |
-          if [[ "${{ inputs.force-tests }}" == "true" ]]; then
-            echo "already_published=false" >> $GITHUB_OUTPUT
+          if [[ "${{ github.event_name }}" == "schedule" || ( "${{ github.event_name }}" == "workflow_dispatch" && "${{ inputs.force-tests }}" == "true" ) ]]; then
+            echo "run_tests=true" >> $GITHUB_OUTPUT
           else
             VERSION=$(jq -r '.version' features/src/${{ matrix.feature }}/devcontainer-feature.json)
             if docker manifest inspect "ghcr.io/postfinance/devcontainer-features/${{ matrix.feature }}:$VERSION" > /dev/null 2>&1; then
-              echo "already_published=true" >> $GITHUB_OUTPUT
+              echo "run_tests=false" >> $GITHUB_OUTPUT
             else
-              echo "already_published=false" >> $GITHUB_OUTPUT
+              echo "run_tests=true" >> $GITHUB_OUTPUT
             fi
           fi
 
       - name: Setup environment
-        if: steps.check-version.outputs.already_published == 'false'
+        if: ${{ steps.check-version.outputs.run_tests == 'true' }}
         uses: ./.github/actions/setup-env
         with:
           go-version: ${{ env.GO_VERSION }}
           node-version: ${{ env.NODE_VERSION }}
 
       - name: Build
-        if: steps.check-version.outputs.already_published == 'false'
+        if: ${{ steps.check-version.outputs.run_tests == 'true' }}
         run: go run ./build --target "Feature:${{ matrix.feature }}:Package"
 
       - name: Test
-        if: steps.check-version.outputs.already_published == 'false'
+        if: ${{ steps.check-version.outputs.run_tests == 'true' }}
         run: go run ./build --target "Feature:${{ matrix.feature }}:Test"
 
   # Publish Job
   publish:
     needs: build
-    if: github.ref == 'refs/heads/main'
+    if: ${{ github.ref == 'refs/heads/main' && github.event_name != 'schedule' }}
     runs-on: ubuntu-latest
     permissions:
       contents: read
